# Puerto del servidor
server.port=8088

# Configuracion de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/DBEmpleado
spring.datasource.username=postgres
spring.datasource.password=huarcaya

# Dialecto de Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Crear o actualizar automaticamente las tablas segun las entidades
spring.jpa.hibernate.ddl-auto=update

# Mostrar consultas SQL en consola
logging.level.org.hibernate.SQL=DEBUG

# Mostrar parametros de las consultas (opcional pero util para depurar)
logging.level.org.hibernate.type.descriptor.sql=TRACE


